### ISSUE TITLE
save font-size to localStorage

### ISSUE THREAD

**Issue by devmartynov** [moztemur/react-font-size-changer#11]
Hi.
Thank you for nice component.
Could you add a very necessary opportunity to save font-size to the localStorage?
Or add optional property "onChange" to component, so that I can save this data myself.

**Comment by moztemur** [comment]
Hi, thanks for your interest. I believe onChange is a better and more flexible solution. I will add it as soon as possible. Or if you wish you can create a PR for this. Any contribution is very welcome.

**Comment by moztemur** [comment]
`onChange(element, newValue, oldValue)` added as of v0.2.0
